services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${GRIMOIRE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GRIMOIRE_POSTGRES_PASSWORD}
      POSTGRES_DB: grimoire
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  axum:
    image: ghcr.io/frederictaillandier/grimoire:nightly
    environment:
      DATABASE_URL: postgres://${GRIMOIRE_POSTGRES_USER}:${GRIMOIRE_POSTGRES_PASSWORD}@postgres:5432/grimoire
      RUST_LOG: info
      LISTENING_ADDRESS: ${LISTENING_ADDRESS}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
